version : '3.7'
services:
  api_hello_world:
    image: orirothschild/hello-world
    ports:
      - '12127:8080'
  api_howdy_world:
    image: orirothschild/howdy-world
    ports:
      - '12128:8080'  