version : '3.7'
services:
  api_hello_world:
    build:
        #only specify the dockerfile name
      dockerfile: Dockerfile
      #location of the dockerfile and where file will be located 
      context: ./docker-ruby-hello-world
    ports:
      - '12127:8080'
  api_howdy_world:
    build:
      dockerfile: Dockerfile
      context: ./docker-ruby-howdy-world
    ports:
      - '12128:8080'  